on:
  pull_request:
    branches: ["main", "releases/**"]
  push:
    branches: ["main", "releases/**", "testing"]

name: Check if pre-commit checks pass

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          pixi-version: v0.70.2
          environments: py312
          frozen: true
      - name: Run pre-commit
        run: pixi run -e py312 pre-commit
